<<<<<<< HEAD
# Generated by Django 5.0.2 on 2024-02-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0005_alter_customuser_user_type_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(3, 'User'), (1, 'admin'), (2, 'doc')], default=1, max_length=50),
        ),
    ]
=======
# Generated by Django 5.0.2 on 2024-02-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0005_alter_customuser_user_type_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(3, 'User'), (1, 'admin'), (2, 'doc')], default=1, max_length=50),
        ),
    ]
>>>>>>> aa4a07f314bd78359b974f32a3cf9dbabf421c1e
