<<<<<<< HEAD
# Generated by Django 5.0.2 on 2024-02-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0006_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_of_appointment',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_of_appointment',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'doc'), (1, 'admin'), (3, 'User')], default=1, max_length=50),
        ),
    ]
=======
# Generated by Django 5.0.2 on 2024-02-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0006_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_of_appointment',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_of_appointment',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'doc'), (1, 'admin'), (3, 'User')], default=1, max_length=50),
        ),
    ]
>>>>>>> aa4a07f314bd78359b974f32a3cf9dbabf421c1e
