<<<<<<< HEAD
# Generated by Django 5.0.2 on 2024-02-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0014_remove_doctorreg_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorreg',
            name='profile_pic',
            field=models.ImageField(default=0, upload_to='media/profile_pic'),
        ),
    ]
=======
# Generated by Django 5.0.2 on 2024-02-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0014_remove_doctorreg_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorreg',
            name='profile_pic',
            field=models.ImageField(default=0, upload_to='media/profile_pic'),
        ),
    ]
>>>>>>> aa4a07f314bd78359b974f32a3cf9dbabf421c1e
